all:
	g++ -g -o AvgTest src/AvgTest.cpp src/ReadBinary.cpp `root-config --cflags --glibs` && ./AvgTest

clear:
	rm -f src/*.o
clean:
	rm -f src/*.o AvgTest                                                      
